export const ordersData = [
  {
    id: "BB-10234",
    customer: "Ayesha Khan",
    phone: "+92 300 1112223",
    email: "ayesha@example.com",
    orderType: "Delivery",
    address: "House 12, Street 5, DHA Phase 2, Lahore",
    items: [
      { name: "Signature Espresso", size: "Medium", qty: 2, price: 3.5 },
      { name: "Butter Croissant", size: "Regular", qty: 1, price: 3.25 },
    ],
    total: 10.25,
    status: "Preparing",
    payment: "Cash",
    date: "Aug 29, 2026",
    time: "10:24 AM",
  },
  {
    id: "BB-10233",
    customer: "Bilal Ahmed",
    phone: "+92 301 2223334",
    email: "bilal@example.com",
    orderType: "Pickup",
    address: null,
    items: [{ name: "Iced Cold Brew", size: "Large", qty: 2, price: 4.75 }],
    total: 9.5,
    status: "Delivered",
    payment: "JazzCash",
    date: "Aug 29, 2026",
    time: "9:10 AM",
  },
  {
    id: "BB-10232",
    customer: "Sara Malik",
    phone: "+92 302 3334445",
    email: "sara@example.com",
    orderType: "Pickup",
    address: null,
    items: [{ name: "Classic Americano", size: "Small", qty: 1, price: 3.25 }],
    total: 3.25,
    status: "Pending",
    payment: "Cash",
    date: "Aug 28, 2026",
    time: "5:45 PM",
  },
  {
    id: "BB-10231",
    customer: "Hamza Tariq",
    phone: "+92 303 4445556",
    email: "hamza@example.com",
    orderType: "Delivery",
    address: "Flat 4B, Askari Tower, Karachi",
    items: [
      { name: "Creamy Cappuccino", size: "Large", qty: 2, price: 5.0 },
      { name: "Mango Smoothie", size: "Medium", qty: 1, price: 5.5 },
      { name: "Butter Croissant", size: "Regular", qty: 2, price: 3.25 },
    ],
    total: 24.75,
    status: "Ready",
    payment: "Easypaisa",
    date: "Aug 28, 2026",
    time: "1:15 PM",
  },
  {
    id: "BB-10230",
    customer: "Zainab Ali",
    phone: "+92 304 5556667",
    email: "zainab@example.com",
    orderType: "Pickup",
    address: null,
    items: [{ name: "Orange Fresh Juice", size: "Medium", qty: 2, price: 4.0 }],
    total: 8.0,
    status: "Cancelled",
    payment: "Card",
    date: "Aug 27, 2026",
    time: "11:30 AM",
  },
  {
    id: "BB-10229",
    customer: "Ahmed Raza",
    phone: "+92 305 6667778",
    email: "ahmed@example.com",
    orderType: "Delivery",
    address: "Office 302, Blue Area, Islamabad",
    items: [{ name: "Artisan Latte", size: "Large", qty: 3, price: 5.5 }],
    total: 16.5,
    status: "Delivered",
    payment: "Cash",
    date: "Aug 27, 2026",
    time: "3:20 PM",
  },
];

export const orderStatuses = [
  "Pending",
  "Preparing",
  "Ready",
  "Delivered",
  "Cancelled",
];
