export const reservationStatuses = ["Pending", "Confirmed", "Cancelled"];

export const reservationsData = [
  {
    id: "RSV-501",
    customerName: "Ayesha Khan",
    phone: "+92 300 1112223",
    email: "ayesha@example.com",
    date: "Aug 29, 2026",
    time: "7:00 PM",
    partySize: 4,
    status: "Confirmed",
    specialRequests: "Window seat if possible, celebrating a birthday.",
  },
  {
    id: "RSV-502",
    customerName: "Bilal Ahmed",
    phone: "+92 301 2223334",
    email: "bilal@example.com",
    date: "Aug 29, 2026",
    time: "1:30 PM",
    partySize: 2,
    status: "Pending",
    specialRequests: "",
  },
  {
    id: "RSV-503",
    customerName: "Sara Malik",
    phone: "+92 302 3334445",
    email: "sara@example.com",
    date: "Aug 30, 2026",
    time: "11:00 AM",
    partySize: 3,
    status: "Confirmed",
    specialRequests: "Bringing a laptop, needs a table near a power outlet.",
  },
  {
    id: "RSV-504",
    customerName: "Hamza Tariq",
    phone: "+92 303 4445556",
    email: "hamza@example.com",
    date: "Aug 31, 2026",
    time: "6:00 PM",
    partySize: 6,
    status: "Pending",
    specialRequests: "Group meeting, would like a private corner.",
  },
  {
    id: "RSV-505",
    customerName: "Zainab Ali",
    phone: "+92 304 5556667",
    email: "zainab@example.com",
    date: "Sep 2, 2026",
    time: "4:00 PM",
    partySize: 2,
    status: "Cancelled",
    specialRequests: "",
  },
];
